spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/okr?useSSL=false
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      org.hibernate.envers.revision_listener: org.burningokr.service.revision.RevisionListener
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true

  environment:
    demo: false

  mail:
    username: bag
    password: bag
    host: smtp.gmail.com
    port: 1234
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
      test-connection: false

  messages:
    basename: messages

system:
  configuration:
    auth-mode: "local"
    api-endpoint: "/api"
    token-endpoint-prefix: ""

