version: '3'

services:
    okr-db:
        image: postgres:9.6.16
        hostname: burning-okr-postgres
        env_file:
            - postgres.env
        ports:
            - 5489:5432
        volumes: 
            - b-okr-pgdata-dev:/var/lib/postgresql/data
        networks:
            - backend-network
    backend:
        image: 'burning-okr:1.0.0-backend'
        build: '../backend/.'
        hostname: burning-okr-backend-dev
        env_file:
            - backend.env
        depends_on:
            - okr-db
        networks:
            - frontend-network
            - backend-network

    frontend:
        image: burning-okr:1.0.0-frontend
        build: '../frontend/.'
        hostname: burning-okr-frontend-dev
        depends_on:
            - backend
        ports:
            - 4200:80
        networks:
            - frontend-network

volumes:
    b-okr-pgdata-dev:

networks:
    frontend-network:
    backend-network:
