apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: b-okr
  name: frontend
  labels:
    app: dev-b-okr-fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-b-okr-fe-app
  template:
    metadata:
      labels:
        app: dev-b-okr-fe-app
    spec:
      containers:
        - name: dev-b-okr-frontend
          image: ghcr.io/burningokr/b-okr-fe-dev:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-credentials