apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${k8s-namespace}
  name: backend
  labels:
    app: dev-b-okr-be-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-b-okr-be-app
  template:
    metadata:
      labels:
        app: dev-b-okr-be-app
    spec:
      containers:
        - name: dev-b-okr-database
          image: postgres:latest
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: ${database-name}
          - name: POSTGRES_USER
            value: ${database-username}
          - name: POSTGRES_PASSWORD
            value: ${database-password}

        - name: dev-b-okr-backend
          image: ghcr.io/b-okr-be-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ${k8s-secret-name}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ${k8s-namespace}
  name: dev-b-okr-persistent-psql-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ${k8s-namespace}
  name: dev-b-okr-persistent-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
