apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: b-okr
  name: b-okr-frontend
  labels:
    app: burning-okr-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burning-okr-frontend-app
  template:
    metadata:
      labels:
        app: burning-okr-frontend-app
    spec:
      containers:
        - name: dev-b-okr-frontend
          image: {{placeholder}}
          imagePullPolicy: Always
          ports: 
            - containerPort: 80
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  namespace: b-okr
  name: burning-okr-frontend-app-service
spec:
  selector:
    app: burning-okr-frontend-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: b-okr
  name: burning-okr-frontend-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{placeholder}}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - burning-okr.dev.bag-k8s.brockhaus-ag.de
      secretName: burning-okr-app-tls
  rules:
    - host: burning-okr.dev.bag-k8s.brockhaus-ag.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: burning-okr-frontend-app-service
                port:
                  number: 80