CREATE TABLE IF NOT EXISTS public.log (
    id BIGINT NOT NULL,
    level CHARACTER VARYING(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_name CHARACTER VARYING(255) NOT NULL,
    line_number CHARACTER VARYING(255) NOT NULL,
    message TEXT,
    CONSTRAINT log_pkey PRIMARY KEY (id)
)