name: build docker-prod-images

on:
  push:
    branches: [master, feat/docker_images_on_github]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
      - name: Read package version
        id: read-version
        run: head -n 1 version.txt || PACKAGE_VERSION=$(sed 's/\d+.\d+.\d+//') && echo ::set-output name=version::$PACKAGE_VERSION

  build-backend-image-dev:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-backend:latest
            ghcr.io/burningokr/b-okr-backend:${{ needs.get-version.outputs.version-no }}
  build-frontend-image-dev:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version-number.outputs.version-no}}
        working-directory: ./frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-frontend:latest
            ghcr.io/burningokr/b-okr-frontend:${{ needs.get-version.outputs.version-no }}
