name: Build and Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read package version
      run: head -n 1 version.txt || PACKAGE_VERSION=$(sed 's/\d+.\d+.\d+//') && echo $PACKAGE_VERSION && echo ::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./backend/burning-okr
    - name: Test
      run: ./gradlew check
      working-directory: ./backend/burning-okr
    - name: Build jar
      run: ./gradlew -PprojVersion="$PACKAGE_VERSION" bootJar
      working-directory: ./backend/burning-okr
    - name: Build war
      run: ./gradlew -PprojVersion="$PACKAGE_VERSION" bootWar
      working-directory: ./backend/burning-okr
    - name: Npm Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Npm Install
      run: npm install
      working-directory: ./frontend
    - name: Npm version
      run: npm version $PACKAGE_VERSION --allow-same-version
      working-directory: ./frontend
    - name: Npm Build
      run: npm run build-prod
      working-directory: ./frontend
    - name: ng lint
      run: npm run lint
      working-directory: ./frontend
    - name: Npm test
      run: npm test
      working-directory: ./frontend

