name: build docker-dev-images

on:
  push:
    branches: [development, feat/docker_images_on_github]
  workflow_dispatch:

env:
  VERSION_NUMBER: 1.${{ github.run_id }}.${{ github.run_number }}

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.get_version_number.outputs.version_no }}
    steps:
    - id: get_version_number
      run: echo "version_no=$VERSION_NUMBER" >> $GITHUB_OUTPUT

  build-backend-image-dev:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-be-dev:latest
            ghcr.io/burningokr/b-okr-be-dev:${{needs.get-version-number.outputs.version-no}}
  build-frontend-image-dev:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version-number.outputs.version-no}}
        working-directory: ./frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-fe-dev:latest
            ghcr.io/burningokr/b-okr-fe-dev:${{needs.get-version-number.outputs.version-no}}
