name: build docker-images

on:
  workflow_call:
    inputs:
      version-number:
        required: true
        type: string
      version-number-major:
        required: true
        type: string
      version-number-minor:
        required: true
        type: string
      version-number-patch:
        required: true
        type: string
      angular-frontend-container-name:
        required: true
        type: string
      spring-backend-container-name:
        required: true
        type: string


jobs:
  build-spring-backend-image:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/${{ inputs.spring-backend-container-name }}:latest
            ghcr.io/burningokr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number }}
            ghcr.io/burningokr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number-major }}
            ghcr.io/burningokr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number-major }}.${{ inputs.version-number-minor }}

  build-angular-frontend-image:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version-number.outputs.version-no}}
        working-directory: ./frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/${{ inputs.angular-frontend-container-name }}:latest
            ghcr.io/burningokr/${{ inputs.angular-frontend-container-name }}:${{ inputs.version-number }}
            ghcr.io/burningokr/${{ inputs.angular-frontend-container-name }}:${{ inputs.version-number-major }}
            ghcr.io/burningokr/${{ inputs.angular-frontend-container-name }}:${{ inputs.version-number-major }}.${{ inputs.version-number-minor }}