name: build docker-prod-images

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
      - name: Remove Windows file endings
        run: vi version.txt -c "set ff=unix" -c ":wq"
      - name: Read package version
        id: read-version
        run: echo version=$(head -n 1 version.txt) >> $GITHUB_OUTPUT

  build-backend-image-prod:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-backend:latest
            ghcr.io/burningokr/b-okr-backend:${{needs.get-version.outputs.version}}
  build-frontend-image-prod:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version.outputs.version}}
        working-directory: ./frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/burningokr/b-okr-frontend:latest
            ghcr.io/burningokr/b-okr-frontend:${{needs.get-version.outputs.version}}
