name: Deploy Dev Kubernetes

on:
  push:
    branches:
      - feat/kubernetes

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.get_version_number.outputs.version_no }}
      version-no-major: ${{ steps.get_major_version_number.outputs.version_no_major }}
      version-no-minor: ${{ steps.get_minor_version_number.outputs.version_no_minor }}
      version-no-patch: ${{ steps.get_patch_version_number.outputs.version_no_patch }}
    steps:
      - id: get_version_number
        run: echo "version_no=$(date +'%y.%m').${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: get_major_version_number
        run: echo "version_no_major=$(cut -d '.' -f 1 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_minor_version_number
        run: echo "version_no_minor=$(cut -d '.' -f 2 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_patch_version_number
        run: echo "version_no_patch=$(cut -d '.' -f 3 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT

  build-dev-images:
    needs: get-version-number
    uses: ./.github/workflows/build-docker-images.yml
    with:
      version-number: ${{ needs.get-version-number.outputs.version-no }}
      version-number-major: ${{ needs.get-version-number.outputs.version-no-major }}
      version-number-minor: ${{ needs.get-version-number.outputs.version-no-minor }}
      version-number-patch: ${{ needs.get-version-number.outputs.version-no-patch }}
      angular-frontend-container-name: "b-okr-fe-dev"
      spring-backend-container-name: "b-okr-be-dev"
    secrets: inherit

  deploy-dev-azure:
    runs-on: ubuntu-latest
    needs: [get-version-number, build-dev-images]
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: "${{ secrets.AZURE_PROJECT }}"
          azure-pipeline-name: "${{ secrets.AZURE_PIPELINES_NAME}}"
          azure-devops-token: "${{ secrets.AZURE_ACCESS_TOKEN }}"
          azure-pipeline-variables: '{"frontend-version": "${{ needs.get-version-number.outputs.version-no }}", "backend-version": "${{ needs.get-version-number.outputs.version-no }}"}'
          
