# This is a basic workflow to help you get started with Actions

name: Release Demo Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add execution privileges
        run: chmod +x ./gradlew
        working-directory: ./backend/burning-okr
      - name: Test
        run: ./gradlew check
        working-directory: ./backend/burning-okr
      - name: Build war
        run: ./gradlew bootWar
        working-directory: ./backend/burning-okr
      - name: Npm Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Npm Install
        run: npm install
        working-directory: ./frontend
      - name: Npm Build
        run: npm run build-docker
        working-directory: ./frontend
      - name: ng lint
        run: npm run lint
        working-directory: ./frontend
      - name: Npm test
        run: npm test
        working-directory: ./frontend


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
