# This is a basic workflow to help you get started with Actions

name: Check Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,mature ]
  pull_request:
    branches: [ master,mature ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Read package version
        run: PACKAGE_VERSION=$(head -n 1 version.txt) && echo $PACKAGE_VERSION && echo ::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: "Check version.txt changed"
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: "version.txt"
          skip-label: "skip version check"
          failure-message: "Missing change in file ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"
      - name: "Check version-form.component.ts changed"
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: "frontend/src/app/core/version-form/version-form.component.ts"
          skip-label: "skip version check"
          failure-message: "Missing change in file ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"
